name: softplan_desafio_tecnico
description: Softplan - Desáfio Técnico

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  shared_preferences: ^0.5.6+2
  flutter_launcher_icons: ^0.7.3
  google_fonts: ^1.1.0
  dio: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/